import { CricketTeam, HostCountry, SquadPlayer } from './types';

export const IPL_HOST_COUNTRY: HostCountry = {
  id: 'ipl_india',
  name: 'India (ICL)',
  shortCode: 'IND',
  flag: '🇮🇳',
  venues: [
    'Wankhede Stadium, Mumbai',
    'M. A. Chidambaram Stadium (Chepauk), Chennai',
    'M. Chinnaswamy Stadium, Bengaluru',
    'Eden Gardens, Kolkata',
    'Narendra Modi Stadium, Ahmedabad',
    'Rajiv Gandhi International Stadium, Hyderabad',
    'Sawai Mansingh Stadium, Jaipur',
    'Arun Jaitley Stadium, New Delhi',
    'BRSABV Ekana Cricket Stadium, Lucknow',
    'HPCA Stadium, Dharamshala',
  ],
};

export const IPL_EDITIONS = [
  {
    id: 'IPL',
    name: 'Indian Cricket League',
    icon: '🏆',
    badge: 'Official League',
    desc: 'Official 10-franchise Indian Cricket League: Single Table, 14 matches per team, Top 4 Playoffs & Grand Final!',
  },
];

export const IPL_TEAMS: CricketTeam[] = [
  // 1. CHENNAI SUPER KINGS
  {
    id: 'csk',
    name: 'Chennai Super Kings',
    shortName: 'CSK',
    flag: '🦁',
    crest: '🦁👑',
    crestIcon: '🦁',
    tagline: 'Whistle Podu • Roaring Lions',
    primaryColor: '#facc15', // Canary Yellow
    secondaryColor: '#1e40af', // Royal Blue
    textColor: '#0f172a',
    accentColor: '#ea580c',
    rating: 94,
    tier: 1,
    description: '5-time champions celebrated for ice-cool leadership, electric Chepauk fortress & legendary finishing.',
    groupSeed: 'A',
  },

  // 2. MUMBAI INDIANS
  {
    id: 'mi',
    name: 'Mumbai Indians',
    shortName: 'MI',
    flag: '🔱',
    crest: '🔱⚡',
    crestIcon: '🔱',
    tagline: 'Duniya Hila Denge • Golden Trident',
    primaryColor: '#004ba0', // Mumbai Blue
    secondaryColor: '#d4af37', // Gold
    textColor: '#ffffff',
    accentColor: '#38bdf8',
    rating: 94,
    tier: 1,
    description: '5-time titans boasting unstoppable power-hitters, Bumrah yorkers & relentless championship pedigree.',
    groupSeed: 'A',
  },

  // 3. ROYAL CHALLENGERS BENGALURU
  {
    id: 'rcb',
    name: 'Royal Challengers Bengaluru',
    shortName: 'RCB',
    flag: '🦅',
    crest: '🦅⚡',
    crestIcon: '🦅',
    tagline: 'Play Bold • Royal Falcon',
    primaryColor: '#b91c1c', // Crimson Red
    secondaryColor: '#0f172a', // Midnight Black
    textColor: '#ffffff',
    accentColor: '#f59e0b',
    rating: 93,
    tier: 1,
    description: 'High-octane fan favorites powered by King Kohli, monstrous six-hitting and Chinnaswamy roar.',
    groupSeed: 'B',
  },

  // 4. KOLKATA KNIGHT RIDERS
  {
    id: 'kkr',
    name: 'Kolkata Knight Riders',
    shortName: 'KKR',
    flag: '⚔️',
    crest: '⚔️🛡️',
    crestIcon: '⚔️',
    tagline: 'Korbo Lorbo Jeetbo • Knight Blades',
    primaryColor: '#3b0764', // Royal Purple
    secondaryColor: '#eab308', // Gold
    textColor: '#ffffff',
    accentColor: '#a855f7',
    rating: 93,
    tier: 1,
    description: 'Defending champions armed with mystery spin wizards, fearless openers and brutal boundary clearers.',
    groupSeed: 'A',
  },

  // 5. SUNRISERS HYDERABAD
  {
    id: 'srh',
    name: 'Sunrisers Hyderabad',
    shortName: 'SRH',
    flag: '🌅',
    crest: '🦅🌅',
    crestIcon: '🦅',
    tagline: 'Orange Army • Rising Sun Falcon',
    primaryColor: '#ea580c', // Orange Army
    secondaryColor: '#0f172a', // Black
    textColor: '#ffffff',
    accentColor: '#f97316',
    rating: 92,
    tier: 1,
    description: 'Ultra-aggressive record-breaking run machines who obliterate bowling attacks from ball one.',
    groupSeed: 'B',
  },

  // 6. RAJASTHAN ROYALS
  {
    id: 'rr',
    name: 'Rajasthan Royals',
    shortName: 'RR',
    flag: '👑',
    crest: '👑🏰',
    crestIcon: '👑',
    tagline: 'Halla Bol • Royal Fortress',
    primaryColor: '#ec4899', // Royal Pink
    secondaryColor: '#1e3a8a', // Royal Blue
    textColor: '#ffffff',
    accentColor: '#f43f5e',
    rating: 91,
    tier: 1,
    description: 'Inaugural champions featuring dynamic strokeplay, deadly powerplay swing and spin mastery.',
    groupSeed: 'A',
  },

  // 7. GUJARAT TITANS
  {
    id: 'gt',
    name: 'Gujarat Titans',
    shortName: 'GT',
    flag: '⚡',
    crest: '⚡🔱',
    crestIcon: '⚡',
    tagline: 'Aava De • Thunder Titans',
    primaryColor: '#0f2b48', // Titans Navy
    secondaryColor: '#d97706', // Gold
    textColor: '#ffffff',
    accentColor: '#38bdf8',
    rating: 90,
    tier: 2,
    description: '2022 champions built on clinical consistency, tactical acumen and world-class spin.',
    groupSeed: 'B',
  },

  // 8. DELHI CAPITALS
  {
    id: 'dc',
    name: 'Delhi Capitals',
    shortName: 'DC',
    flag: '🐅',
    crest: '🐅🏛️',
    crestIcon: '🐅',
    tagline: 'Roar Macha • Imperial Tigers',
    primaryColor: '#1d4ed8', // Capitals Blue
    secondaryColor: '#dc2626', // Red
    textColor: '#ffffff',
    accentColor: '#60a5fa',
    rating: 90,
    tier: 2,
    description: 'Fearless youngsters and audacious hitters capable of pulling off unbelievable chases.',
    groupSeed: 'A',
  },

  // 9. LUCKNOW SUPER GIANTS
  {
    id: 'lsg',
    name: 'Lucknow Super Giants',
    shortName: 'LSG',
    flag: '🏹',
    crest: '🏹🦅',
    crestIcon: '🏹',
    tagline: 'Ab Apni Baari Hai • Celestial Bow',
    primaryColor: '#0284c7', // Sky Blue
    secondaryColor: '#b91c1c', // Burgundy
    textColor: '#ffffff',
    accentColor: '#38bdf8',
    rating: 89,
    tier: 2,
    description: 'Tenacious competitors with lightning 156 km/h pace bowling and venomous lower-order power.',
    groupSeed: 'B',
  },

  // 10. PUNJAB KINGS
  {
    id: 'pbks',
    name: 'Punjab Kings',
    shortName: 'PBKS',
    flag: '🦁',
    crest: '🦁👑',
    crestIcon: '🦁',
    tagline: 'Sadda Punjab • Royal Shers',
    primaryColor: '#dc2626', // Crimson Red
    secondaryColor: '#64748b', // Silver
    textColor: '#ffffff',
    accentColor: '#f59e0b',
    rating: 88,
    tier: 2,
    description: 'Unpredictable thrillers renowned for death-over nail-biters and record T20 run chases.',
    groupSeed: 'B',
  },
];

export const IPL_SQUADS: Record<string, SquadPlayer[]> = {
  csk: [
    { id: 'csk_1', name: 'Ruturaj Gaikwad', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'csk_2', name: 'MS Dhoni', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'csk_3', name: 'Ravindra Jadeja', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'csk_4', name: 'Shivam Dube', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Medium' },
    { id: 'csk_5', name: 'Rachin Ravindra', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'csk_6', name: 'Ajinkya Rahane', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'csk_7', name: 'Daryl Mitchell', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium' },
    { id: 'csk_8', name: 'Moeen Ali', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'csk_9', name: 'Matheesha Pathirana', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast (Sling)' },
    { id: 'csk_10', name: 'Deepak Chahar', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'csk_11', name: 'Shardul Thakur', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'csk_12', name: 'Tushar Deshpande', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'csk_13', name: 'Maheesh Theekshana', role: 'BOWLER', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'csk_14', name: 'Sameer Rizvi', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'csk_15', name: 'Mukesh Choudhary', role: 'BOWLER', bowlingStyle: 'Left-Arm Medium Fast' },
  ],
  mi: [
    { id: 'mi_1', name: 'Hardik Pandya', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast Medium' },
    { id: 'mi_2', name: 'Rohit Sharma', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'mi_3', name: 'Suryakumar Yadav', role: 'BATSMAN', battingStyle: 'Right-Hand Bat (360°)' },
    { id: 'mi_4', name: 'Jasprit Bumrah', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'mi_5', name: 'Ishan Kishan', role: 'WICKET_KEEPER', battingStyle: 'Left-Hand Bat' },
    { id: 'mi_6', name: 'Tilak Varma', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'mi_7', name: 'Tim David', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'mi_8', name: 'Romario Shepherd', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast Medium' },
    { id: 'mi_9', name: 'Gerald Coetzee', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'mi_10', name: 'Piyush Chawla', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'mi_11', name: 'Nuwan Thushara', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast Medium (Sling)' },
    { id: 'mi_12', name: 'Akash Madhwal', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'mi_13', name: 'Mohammad Nabi', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'mi_14', name: 'Nehal Wadhera', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'mi_15', name: 'Dewald Brevis', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
  ],
  rcb: [
    { id: 'rcb_1', name: 'Faf du Plessis', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'rcb_2', name: 'Virat Kohli', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'rcb_3', name: 'Glenn Maxwell', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'rcb_4', name: 'Rajat Patidar', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'rcb_5', name: 'Cameron Green', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast Medium' },
    { id: 'rcb_6', name: 'Dinesh Karthik', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'rcb_7', name: 'Will Jacks', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'rcb_8', name: 'Mahipal Lomror', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'rcb_9', name: 'Mohammed Siraj', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'rcb_10', name: 'Yash Dayal', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast Medium' },
    { id: 'rcb_11', name: 'Lockie Ferguson', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast (150+ km/h)' },
    { id: 'rcb_12', name: 'Karn Sharma', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'rcb_13', name: 'Swapnil Singh', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'rcb_14', name: 'Anuj Rawat', role: 'WICKET_KEEPER', battingStyle: 'Left-Hand Bat' },
    { id: 'rcb_15', name: 'Reece Topley', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast Medium' },
  ],
  kkr: [
    { id: 'kkr_1', name: 'Shreyas Iyer', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'kkr_2', name: 'Sunil Narine', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Off Spin (Mystery)' },
    { id: 'kkr_3', name: 'Andre Russell', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast' },
    { id: 'kkr_4', name: 'Phil Salt', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'kkr_5', name: 'Rinku Singh', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'kkr_6', name: 'Venkatesh Iyer', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Medium' },
    { id: 'kkr_7', name: 'Mitchell Starc', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast' },
    { id: 'kkr_8', name: 'Varun Chakaravarthy', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin (Mystery)' },
    { id: 'kkr_9', name: 'Harshit Rana', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast Medium' },
    { id: 'kkr_10', name: 'Vaibhav Arora', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'kkr_11', name: 'Ramandeep Singh', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium' },
    { id: 'kkr_12', name: 'Nitish Rana', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'kkr_13', name: 'Rahmanullah Gurbaz', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'kkr_14', name: 'Suyash Sharma', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'kkr_15', name: 'Anukul Roy', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
  ],
  srh: [
    { id: 'srh_1', name: 'Pat Cummins', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Fast' },
    { id: 'srh_2', name: 'Travis Head', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'srh_3', name: 'Heinrich Klaasen', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'srh_4', name: 'Abhishek Sharma', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'srh_5', name: 'Nitish Kumar Reddy', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'srh_6', name: 'Aiden Markram', role: 'BATSMAN', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'srh_7', name: 'Bhuvneshwar Kumar', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast (Swing)' },
    { id: 'srh_8', name: 'T Natarajan', role: 'BOWLER', bowlingStyle: 'Left-Arm Medium Fast (Yorker)' },
    { id: 'srh_9', name: 'Shahbaz Ahmed', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'srh_10', name: 'Jaydev Unadkat', role: 'BOWLER', bowlingStyle: 'Left-Arm Medium' },
    { id: 'srh_11', name: 'Abdul Samad', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'srh_12', name: 'Mayank Markande', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'srh_13', name: 'Washington Sundar', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'srh_14', name: 'Glenn Phillips', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'srh_15', name: 'Rahul Tripathi', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
  ],
  rr: [
    { id: 'rr_1', name: 'Sanju Samson', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'rr_2', name: 'Yashasvi Jaiswal', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'rr_3', name: 'Jos Buttler', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'rr_4', name: 'Riyan Parag', role: 'BATSMAN', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'rr_5', name: 'Shimron Hetmyer', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'rr_6', name: 'Dhruv Jurel', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'rr_7', name: 'Trent Boult', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast (In-Swing)' },
    { id: 'rr_8', name: 'Yuzvendra Chahal', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'rr_9', name: 'Ravichandran Ashwin', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'rr_10', name: 'Avesh Khan', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'rr_11', name: 'Sandeep Sharma', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'rr_12', name: 'Rovman Powell', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'rr_13', name: 'Nandre Burger', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast' },
    { id: 'rr_14', name: 'Kuldeep Sen', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'rr_15', name: 'Shubham Dubey', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
  ],
  gt: [
    { id: 'gt_1', name: 'Shubman Gill', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'gt_2', name: 'Sai Sudharsan', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'gt_3', name: 'David Miller', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'gt_4', name: 'Rashid Khan', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Leg Spin (Googly)' },
    { id: 'gt_5', name: 'Rahul Tewatia', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'gt_6', name: 'Shahrukh Khan', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'gt_7', name: 'Wriddhiman Saha', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'gt_8', name: 'Kane Williamson', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'gt_9', name: 'Noor Ahmad', role: 'BOWLER', bowlingStyle: 'Left-Arm Wrist Spin' },
    { id: 'gt_10', name: 'Mohit Sharma', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast (Back of Hand)' },
    { id: 'gt_11', name: 'Spencer Johnson', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast' },
    { id: 'gt_12', name: 'Umesh Yadav', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'gt_13', name: 'R. Sai Kishore', role: 'BOWLER', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'gt_14', name: 'Sandeep Warrier', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'gt_15', name: 'Vijay Shankar', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium' },
  ],
  dc: [
    { id: 'dc_1', name: 'Rishabh Pant', role: 'WICKET_KEEPER', battingStyle: 'Left-Hand Bat' },
    { id: 'dc_2', name: 'Jake Fraser-McGurk', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'dc_3', name: 'Tristan Stubbs', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'dc_4', name: 'Axar Patel', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'dc_5', name: 'David Warner', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'dc_6', name: 'Kuldeep Yadav', role: 'BOWLER', bowlingStyle: 'Left-Arm Wrist Spin' },
    { id: 'dc_7', name: 'Khaleel Ahmed', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast Medium' },
    { id: 'dc_8', name: 'Mukesh Kumar', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'dc_9', name: 'Abishek Porel', role: 'WICKET_KEEPER', battingStyle: 'Left-Hand Bat' },
    { id: 'dc_10', name: 'Anrich Nortje', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast (150+ km/h)' },
    { id: 'dc_11', name: 'Prithvi Shaw', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'dc_12', name: 'Ishant Sharma', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast Medium' },
    { id: 'dc_13', name: 'Lalit Yadav', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'dc_14', name: 'Shai Hope', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'dc_15', name: 'Rasikh Dar', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
  ],
  lsg: [
    { id: 'lsg_1', name: 'KL Rahul', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'lsg_2', name: 'Nicholas Pooran', role: 'WICKET_KEEPER', battingStyle: 'Left-Hand Bat' },
    { id: 'lsg_3', name: 'Marcus Stoinis', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Medium' },
    { id: 'lsg_4', name: 'Mayank Yadav', role: 'BOWLER', bowlingStyle: 'Right-Arm Express (156 km/h)' },
    { id: 'lsg_5', name: 'Quinton de Kock', role: 'WICKET_KEEPER', battingStyle: 'Left-Hand Bat' },
    { id: 'lsg_6', name: 'Ayush Badoni', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'lsg_7', name: 'Krunal Pandya', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'lsg_8', name: 'Ravi Bishnoi', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'lsg_9', name: 'Naveen-ul-Haq', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'lsg_10', name: 'Mohsin Khan', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast Medium' },
    { id: 'lsg_11', name: 'Yash Thakur', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium Fast' },
    { id: 'lsg_12', name: 'Deepak Hooda', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Off Spin' },
    { id: 'lsg_13', name: 'Devdutt Padikkal', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'lsg_14', name: 'Amit Mishra', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'lsg_15', name: 'Shamar Joseph', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
  ],
  pbks: [
    { id: 'pbks_1', name: 'Shikhar Dhawan', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
    { id: 'pbks_2', name: 'Shashank Singh', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'pbks_3', name: 'Ashutosh Sharma', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'pbks_4', name: 'Sam Curran', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Left-Arm Medium Fast' },
    { id: 'pbks_5', name: 'Arshdeep Singh', role: 'BOWLER', bowlingStyle: 'Left-Arm Fast Medium (Swing)' },
    { id: 'pbks_6', name: 'Jonny Bairstow', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'pbks_7', name: 'Prabhsimran Singh', role: 'BATSMAN', battingStyle: 'Right-Hand Bat' },
    { id: 'pbks_8', name: 'Jitesh Sharma', role: 'WICKET_KEEPER', battingStyle: 'Right-Hand Bat' },
    { id: 'pbks_9', name: 'Kagiso Rabada', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast' },
    { id: 'pbks_10', name: 'Harshal Patel', role: 'BOWLER', bowlingStyle: 'Right-Arm Medium (Slower)' },
    { id: 'pbks_11', name: 'Rahul Chahar', role: 'BOWLER', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'pbks_12', name: 'Harpreet Brar', role: 'ALL_ROUNDER', battingStyle: 'Left-Hand Bat', bowlingStyle: 'Slow Left-Arm Orthodox' },
    { id: 'pbks_13', name: 'Liam Livingstone', role: 'ALL_ROUNDER', battingStyle: 'Right-Hand Bat', bowlingStyle: 'Right-Arm Leg Spin' },
    { id: 'pbks_14', name: 'Nathan Ellis', role: 'BOWLER', bowlingStyle: 'Right-Arm Fast Medium' },
    { id: 'pbks_15', name: 'Rilee Rossouw', role: 'BATSMAN', battingStyle: 'Left-Hand Bat' },
  ],
};
